# Generated by Django 2.0.6 on 2018-10-08 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodscategorybrand',
            old_name='cagetory',
            new_name='category',
        ),
    ]
