# Generated by Django 2.0.6 on 2018-10-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20181008_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='categorys',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='goodscategorybrand',
            old_name='categorys',
            new_name='category',
        ),
    ]
